-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 18:51:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clickbusbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clickbusbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clickbusbd` DEFAULT CHARACTER SET utf8 ;
USE `clickbusbd` ;

-- -----------------------------------------------------
-- Table `clickbusbd`.`contatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clickbusbd`.`contatos` ;

CREATE TABLE IF NOT EXISTS `clickbusbd`.`contatos` (
  `contato_id` INT NOT NULL AUTO_INCREMENT,
  `email` NVARCHAR(255) NOT NULL,
  `nome` NVARCHAR(255) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_termino` DATETIME NOT NULL,
  `agente` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `origem` VARCHAR(25) NOT NULL,
  `semana` INT NOT NULL,
  `semana_nome` VARCHAR(15) NOT NULL,
  `data_importacao` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`contato_id`),
  UNIQUE INDEX `unq_interacao` (`email` ASC, `origem` ASC, `data_inicio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbusbd`.`log_erros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clickbusbd`.`log_erros` ;

CREATE TABLE IF NOT EXISTS `clickbusbd`.`log_erros` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_mensagem` TEXT NOT NULL,
  `log_data` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
